export const CHANGE_MOBILE_MODE = "CHANGE_MOBILE_MODE";

export const INNIT_EVENTS = "INNIT_EVENTS";
export const SET_ONLINE_CLIENT_STATUS = "SET_ONLINE_CLIENT_STATUS";
export const SET_OFFLINE_CLIENT_STATUS = "SET_OFFLINE_CLIENT_STATUS";

export const CHANGE_MEDIA_QUERY = "CHECK_MEDIA_QUERY";

export const SET_DARK_THEME = "SET_DARK_THEME";
export const SET_LIGHT_THEME = "SET_LIGHT_THEME";

export const LOGIN_START = "AUTH/LOGIN_START"
export const GOOGLE_LOGIN_SUCCESS = "AUTH/GOOGLE_LOGIN_SUCCESS"
export const LOAD_IMAGE = "AUTH/LOAD_IMAGE"
export const LOGIN_SUCCESS = "AUTH/LOGIN_SUCCESS"
export const LOGIN_ERROR = "AUTH/LOGIN_ERROR"

export const CONNECT_TO_LOBBY = "CONNECT_TO_LOBBY"
export const LEAVE_LOBBY = "LEAVE_LOBBY"
export const SET_LOBBY_INFO = "SET_LOBBY_INFO"

export const INNIT_PEER = "INNIT_PEER";
export const SET_PEER = "SET_PEER";
export const CONNECT_TO_PEER = "CONNECT_TO_PEER";
export const SEND_PEER_DATA = "SEND_PEER_DATA";
export const PEER_PROVIDER_OPEN = "PEER_PROVIDER_OPEN";
export const PEER_CONNECTION_FROM_OPEN = "PEER_CONNECTION_FROM_OPEN";
export const PEER_CONNECTION_FROM_CLOSE = "PEER_CONNECTION_FROM_CLOSE";
export const PEER_CONNECTION_TO_OPEN = "PEER_CONNECTION_TO_OPEN";

export const ADD_PEER_CONNECTION = "ADD_PEER_CONNECTION";
export const AUTHORIZE_PEER_USER = "AUTHORIZE_PEER_USER";
